/*
 * This file is generated by jOOQ.
 */
package com.example.demo.accountms.domain.projections;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * 帳戶資料
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "bank_account",
    uniqueConstraints = {
        @UniqueConstraint(name = "KEY_bank_account_PRIMARY", columnNames = { "account_number" })
    }
)
@JsonIgnoreProperties(ignoreUnknown = true, value = {"hibernateLazyInitializer", "handler", "fieldHandler"})
public class BankAccount implements Serializable {

    private static final long serialVersionUID = 1L;

    private String        accountNumber;
    private Integer       balance;
    private String        customer;
    private String        createdBy;
    private LocalDateTime createdDate;
    private String        lastModifiedBy;
    private LocalDateTime lastModifiedDate;

    public BankAccount() {}

    public BankAccount(BankAccount value) {
        this.accountNumber = value.accountNumber;
        this.balance = value.balance;
        this.customer = value.customer;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.lastModifiedBy = value.lastModifiedBy;
        this.lastModifiedDate = value.lastModifiedDate;
    }

    public BankAccount(
        String        accountNumber,
        Integer       balance,
        String        customer,
        String        createdBy,
        LocalDateTime createdDate,
        String        lastModifiedBy,
        LocalDateTime lastModifiedDate
    ) {
        this.accountNumber = accountNumber;
        this.balance = balance;
        this.customer = customer;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * Getter for <code>bank_account.account_number</code>. 帳號
     */
    @Id
    @Column(name = "account_number", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getAccountNumber() {
        return this.accountNumber;
    }

    /**
     * Setter for <code>bank_account.account_number</code>. 帳號
     */
    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * Getter for <code>bank_account.balance</code>. 餘額
     */
    @Column(name = "balance", nullable = false, precision = 10)
    @NotNull
    public Integer getBalance() {
        return this.balance;
    }

    /**
     * Setter for <code>bank_account.balance</code>. 餘額
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * Getter for <code>bank_account.customer</code>. 客戶
     */
    @Column(name = "customer", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getCustomer() {
        return this.customer;
    }

    /**
     * Setter for <code>bank_account.customer</code>. 客戶
     */
    public void setCustomer(String customer) {
        this.customer = customer;
    }

    /**
     * Getter for <code>bank_account.created_by</code>.
     */
    @Column(name = "created_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>bank_account.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>bank_account.created_date</code>.
     */
    @Column(name = "created_date", nullable = false)
    @NotNull
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>bank_account.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>bank_account.last_modified_by</code>.
     */
    @Column(name = "last_modified_by", nullable = false, length = 60)
    @NotNull
    @Size(max = 60)
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    /**
     * Setter for <code>bank_account.last_modified_by</code>.
     */
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * Getter for <code>bank_account.last_modified_date</code>.
     */
    @Column(name = "last_modified_date", nullable = false)
    @NotNull
    public LocalDateTime getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    /**
     * Setter for <code>bank_account.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}