/**
 * This package encloses all the inbound interfaces to our bounded context classified by the communication protocol. The main purpose of interfaces is to negotiate the protocol on behalf of the Domain Model (e.g., REST API(s), WebSocket(s), FTP(s), Custom Protocol).
 * <p>
 * As an example, the Booking Command Bounded Context provides REST APIs <br>
 * for sending Commands to it (e.g., Book Cargo Command, Update Cargo Command). <br>
 * Similarly, the Booking Query Bounded Context provides REST APIs for sending Queries <br>
 * to it (e.g., Retrieve Cargo Booking Details, List all Cargos). This is grouped into the <br>
 * “rest” package. It also has Event Handlers which subscribe to the various Events that are <br>
 * generated by Axon. All Event Handlers are grouped into the “eventhandlers” package. <br>
 *
 * In addition to these two packages, the interface package also contains the “transform” <br>
 * package. This is used to translate the incoming API Resource/Event data to the <br>
 * corresponding Command/Query model. <br>
 * 
 * @since 1.0
 * @author sam
 * @version 1.0
 */
package com.example.demo.accountms.interfaces;
